version: '3'
services:

  #PHP Service
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: interview-assessment/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: ngnx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - server-network

#Docker Networks
networks:
  app-network:
    driver: bridge